package javaapplication4;

import static javaapplication4.conexao.con;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;


/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author User
 */
public class estoque extends javax.swing.JFrame {

    /**
     * Creates new form estoque
     */
    public estoque() {
        initComponents();
        conexao.Conectar();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jButton4 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        racao = new javax.swing.JRadioButton();
        acessorios = new javax.swing.JRadioButton();
        saude = new javax.swing.JRadioButton();
        jButton6 = new javax.swing.JButton();
        NOME = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        PRECO = new javax.swing.JTextField();
        QNTD = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        CODIGO = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jButton7 = new javax.swing.JButton();

        jLabel2.setText("jLabel2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton4.setText("Voltar");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton1.setText("Cadastrar Itens");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Nirmala UI Semilight", 1, 24)); // NOI18N
        jLabel5.setText("Estoque");

        buttonGroup2.add(racao);
        racao.setText("Ração");
        racao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                racaoActionPerformed(evt);
            }
        });

        buttonGroup2.add(acessorios);
        acessorios.setText("Acessórios");

        buttonGroup2.add(saude);
        saude.setText("Saúde e Higiene");
        saude.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saudeActionPerformed(evt);
            }
        });

        jButton6.setText("Consultar Item");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jLabel3.setText("Preço :");

        jLabel4.setText("Quantidade :");

        PRECO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PRECOActionPerformed(evt);
            }
        });

        jLabel6.setText("Código do Item :");

        CODIGO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CODIGOActionPerformed(evt);
            }
        });

        jLabel7.setText("Nome do Item :");

        jButton7.setText("Alterar opções do Item");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(118, 118, 118)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(192, 192, 192)
                        .addComponent(jLabel5)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(31, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel7)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(NOME, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jButton6))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(92, 92, 92)
                                    .addComponent(acessorios)
                                    .addGap(18, 18, 18)
                                    .addComponent(saude))
                                .addComponent(racao))
                            .addGap(50, 50, 50)))
                    .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 425, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(32, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(CODIGO, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(PRECO, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(QNTD, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton7)
                        .addGap(48, 48, 48)
                        .addComponent(jButton1)
                        .addGap(25, 25, 25))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NOME, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton6)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(racao)
                    .addComponent(acessorios)
                    .addComponent(saude))
                .addGap(18, 18, 18)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(CODIGO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(PRECO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(QNTD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 73, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton4)
                    .addComponent(jButton1)
                    .addComponent(jButton7))
                .addGap(27, 27, 27))
        );

        setSize(new java.awt.Dimension(504, 465));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        CadastroItem caditem = new CadastroItem();
        caditem.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        Menu menu = new Menu();
        menu.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void racaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_racaoActionPerformed

    }//GEN-LAST:event_racaoActionPerformed

    private void saudeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saudeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_saudeActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
      
        String sql;
       
       
     if(racao.isSelected()){  
     
        try{
        sql = "select * from Estoque where NOME = '" + NOME.getText() + "' order by CODIGO desc"; //cria a instrução de pesquisa
        //a partir do nome digitado no campo tfNome
        
        Statement stm = con.createStatement(); //cria uma declaracao stm para a variavel con de conexao
        ResultSet rs = stm.executeQuery(sql); // cria uma variavel rs como resultset (resultado) da execucao da consulta sql
        rs.first();  //move o ponteiro do BD para o primeiro registro
        
        String[] linha= new String[]{rs.getString("CODIGO"),rs.getString("PRECO"),
            rs.getString("NOME"),rs.getString("QNTD")}; // cria um vetor chmado linha que contem o resultado da pesquisa com todos os campos
        
       
        
           NOME.setText(rs.getString("NOME")); 
           CODIGO.setText(rs.getString("CODIGO"));
           PRECO.setText(rs.getString("PRECO"));
           QNTD.setText(rs.getString("QNTD"));
  
      
           
        while(rs.next()){
            linha= new String[]{rs.getString("CODIGO"),rs.getString("PRECO"),
            rs.getString("NOME"),rs.getString("QNTD")};
            //cada vez que passar pelo while cria uma variavel linha contendo o conteudo dos campos do BD
            //e joga dentro do vetor chamado linha
                       
        }
        
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, "Erro ao consultar, tente novamente"
                    ,"ERRO",JOptionPane.INFORMATION_MESSAGE);
            //mostra caixa de mensagem de erro com icone de informacao
        }     
     }
          if(acessorios.isSelected()){  
              
        try{
        sql = "select * from Acessorios where NOME = '" + NOME.getText() + "' order by CODIGO desc"; //cria a instrução de pesquisa
        //a partir do nome digitado no campo tfNome
        
        Statement stm = con.createStatement(); //cria uma declaracao stm para a variavel con de conexao

        ResultSet rs = stm.executeQuery(sql); // cria uma variavel rs como resultset (resultado) da execucao da consulta sql
        rs.first();  //move o ponteiro do BD para o primeiro registro
        
        String[] linha= new String[]{rs.getString("CODIGO"),rs.getString("PRECO"),
            rs.getString("NOME"),rs.getString("QNTD")}; // cria um vetor chmado linha que contem o resultado da pesquisa com todos os campos
        
       
        
           NOME.setText(rs.getString("NOME")); 
           CODIGO.setText(rs.getString("CODIGO"));
           PRECO.setText(rs.getString("PRECO"));
           QNTD.setText(rs.getString("QNTD"));
  
      
           
        while(rs.next()){
            linha= new String[]{rs.getString("CODIGO"),rs.getString("PRECO"),
            rs.getString("NOME"),rs.getString("QNTD")};
            //cada vez que passar pelo while cria uma variavel linha contendo o conteudo dos campos do BD
            //e joga dentro do vetor chamado linha
                       
        }
        
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, "Erro ao consultar, tente novamente"
                    ,"ERRO",JOptionPane.INFORMATION_MESSAGE);
            //mostra caixa de mensagem de erro com icone de informacao
        }     
     }
            if(saude.isSelected()){  
               
        try{
        sql = "select * from Saude where NOME = '" + NOME.getText() + "' order by CODIGO desc"; //cria a instrução de pesquisa
        //a partir do nome digitado no campo tfNome
        
        Statement stm = con.createStatement(); //cria uma declaracao stm para a variavel con de conexao

        ResultSet rs = stm.executeQuery(sql); // cria uma variavel rs como resultset (resultado) da execucao da consulta sql
        rs.first();  //move o ponteiro do BD para o primeiro registro
        
        String[] linha= new String[]{rs.getString("CODIGO"),rs.getString("PRECO"),
            rs.getString("NOME"),rs.getString("QNTD")}; // cria um vetor chmado linha que contem o resultado da pesquisa com todos os campos
        
       
        
           NOME.setText(rs.getString("NOME")); 
           CODIGO.setText(rs.getString("CODIGO"));
           PRECO.setText(rs.getString("PRECO"));
           QNTD.setText(rs.getString("QNTD"));
  
      
           
        while(rs.next()){
            linha= new String[]{rs.getString("CODIGO"),rs.getString("PRECO"),
            rs.getString("NOME"),rs.getString("QNTD")};
            //cada vez que passar pelo while cria uma variavel linha contendo o conteudo dos campos do BD
            //e joga dentro do vetor chamado linha
                       
        }
        
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, "Erro ao consultar, tente novamente"
                    ,"ERRO",JOptionPane.INFORMATION_MESSAGE);
            //mostra caixa de mensagem de erro com icone de informacao
        }     
     } 
    }//GEN-LAST:event_jButton6ActionPerformed

    private void CODIGOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CODIGOActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CODIGOActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
         
        String sql;
        
        String nome;
        int codigo, qntd;
        float preco;
        
   if(racao.isSelected()){      
 try{
       sql = "update Estoque set NOME = '" + NOME.getText() + "', CODIGO = " + Integer.parseInt(CODIGO.getText()) + ", PRECO = " + Float.parseFloat(PRECO.getText()) +
          ", QNTD = " + Integer.parseInt(QNTD.getText()) + " where NOME = '" + NOME.getText() + "'";
        
        
            Statement stm = con.prepareStatement(sql);
            stm.execute(sql);
            
  
            NOME.setText("");
            PRECO.setText("");
            CODIGO.setText("");
            QNTD.setText("");
            NOME.requestFocus();
            JOptionPane.showMessageDialog(null,"Dados alterados com Sucesso");                              
        }
             
        catch(Exception e){
            
            JOptionPane.showMessageDialog(null, "Erro ao alterar, tente novamente" + e,"ERRO",JOptionPane.INFORMATION_MESSAGE);
            
        }           // TODO add your handling code here:
    }//GEN-LAST:event_jButton7ActionPerformed
       
   
   if(acessorios.isSelected()){      
 try{
       sql = "update Acessorios set NOME = '" + NOME.getText() + "', CODIGO = " + Integer.parseInt(CODIGO.getText()) + ", PRECO = " + Float.parseFloat(PRECO.getText()) +
          ", QNTD = " + Integer.parseInt(QNTD.getText()) + " where NOME = '" + NOME.getText() + "'";
        
        
            Statement stm = con.prepareStatement(sql);
            stm.execute(sql);
           
  
            NOME.setText("");
            PRECO.setText("");
            CODIGO.setText("");
            QNTD.setText("");
            NOME.requestFocus();
            JOptionPane.showMessageDialog(null,"Dados alterados com Sucesso");  
                                          
        }
             
        catch(Exception e){
            
            JOptionPane.showMessageDialog(null, "Erro ao alterar, tente novamente" + e,"ERRO",JOptionPane.INFORMATION_MESSAGE);
            
        }           // TODO add your handling code here:
    } 
          if(saude.isSelected()){      
 try{
       sql = "update Saude set NOME = '" + NOME.getText() + "', CODIGO = " + Integer.parseInt(CODIGO.getText()) + ", PRECO = " + Float.parseFloat(PRECO.getText()) +
          ", QNTD = " + Integer.parseInt(QNTD.getText()) + " where NOME = '" + NOME.getText() + "'";
        
        
            Statement stm = con.prepareStatement(sql);
            stm.execute(sql);
           
  
            NOME.setText("");
            PRECO.setText("");
            CODIGO.setText("");
            QNTD.setText("");
            NOME.requestFocus();
            JOptionPane.showMessageDialog(null,"Dados alterados com Sucesso");  
                                          
        }
             
        catch(Exception e){
            
            JOptionPane.showMessageDialog(null, "Erro ao alterar, tente novamente" + e,"ERRO",JOptionPane.INFORMATION_MESSAGE);
            
        }           // TODO add your handling code here:
    } 
        
    
    }
    
    
        
 
    
    private void PRECOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PRECOActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PRECOActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(estoque.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(estoque.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(estoque.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(estoque.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new estoque().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField CODIGO;
    private javax.swing.JTextField NOME;
    private javax.swing.JTextField PRECO;
    private javax.swing.JTextField QNTD;
    private javax.swing.JRadioButton acessorios;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JRadioButton racao;
    private javax.swing.JRadioButton saude;
    // End of variables declaration//GEN-END:variables
}
